apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: my-java-app-dc
  namespace: test
  labels:
    app: my-java-app-dc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-java-app-dc
    spec:
      containers:
      - name: my-java-app
        image: registry.access.redhat.com/ubi8/openjdk-17:1.11
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTIONS
          value: "-Xmx256m -Xms256m"
  strategy:
    type: Rolling
    rollingParams:
      maxSurge: 25%
      maxUnavailable: 25%
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - my-java-app
      from:
        kind: ImageStreamTag
        name: openjdk-17:latest
